use experiment;
insert into sigcodes(id,name,meaning) values
(1,'1°','1 hour, 2 hours, etc.'),
(2,'2°','1 hour, 2 hours, etc.'),
(3,'a','before'),
(4,'aa','of each'),
(5,'ac','before meals ("before a meal" if once daily dosing)'),
(6,'ad','right ear'),
(7,'ad','as directed (used occasionally in error)'),
(8,'AM','morning'),
(9,'amp','ampules'),
(10,'apl','applicatorful (for vaginal creams)'),
(11,'aq','water'),
(12,'as','left ear'),
(13,'au','both ears  '),
(14,'bid','twice daily'),
(15,'c','with'),
(16,'C','100'),
(17,'cap','capsule(s)'),
(18,'cc','cubic centimeter (same as milliliter or ml)'),
(19,'cd','cycle day (menstrual cycle)'),
(20,'cid','fives times daily (rarely used now)'),
(21,'cmpd','compound'),
(22,'cr','cream'),
(23,'d','daily or day'),
(24,'DAW','Dispense as Written (no generic)'),
(25,'DC','discontinue (or discharge from hospital)'),
(26,'dc','discontinue (or discharge from hospital)'),
(27,'d/c','discontinue (or discharge from hospital)'),
(28,'disp','dispense'),
(29,'DS','double strength'),
(30,'dx','diagnosis'),
(31,'elix','elixir'),
(32,'eq','equivalent'),
(33,'et','and'),
(34,'fid','five times daily'),
(35,'5x/d','five times daily'),
(36,'g','gram'),
(37,'gm','gram'),
(38,'gen','generic'),
(39,'gr','grain, about 60 mg '),
(40,'gtt','drop(s)'),
(41,'h','hour(s)'),
(42,'hr','hour(s)'),
(43,'HD','high dose'),
(44,'hs','at bedtime'),
(45,'H2O','water'),
(46,'IM','intramuscularly (for injectables)'),
(47,'inj','inject, injection'),
(48,'IU','international units'),
(49,'IV','intravenously (for injectables)'),
(50,'kg','kilogram'),
(51,'l','liter(s)'),
(52,'liq','liquid'),
(53,'lot','lotion'),
(54,'max','maximum'),
(55,'MDI','(metered dose) inhaler'),
(56,'meq','milliequivalent(s)'),
(57,'mEq','milliequivalent(s)'),
(58,'mcg','microgram'),
(59,'µg','microgram'),
(60,'mg','milligram(s)'),
(61,'min','minute'),
(62,'min','minimum'),
(63,'ml','milliliter(s)'),
(64,'mm','millimeters'),
(65,'mo','month'),
(66,'neb','nebulizer'),
(67,'noct','night'),
(68,'npo','nothing by mouth'),
(69,'NPO','nothing by mouth'),
(70,'nr','no refills'),
(71,'od','right eye (or once daily)'),
(72,'os','left eye'),
(73,'ou','both eyes'),
(74,'oz','ounce'),
(75,'p','after'),
(76,'pc','after meals  ("after a meal" if once daily dosing)'),
(77,'pc breakfast','after breakfast'),
(78,'per','per (per day, week, month or other time period)'),
(79,'per','in (in nebulizer, in rectum, in vagina)'),
(80,'PM','evening or nighttime'),
(81,'po','by mouth'),
(82,'per os','by mouth'),
(83,'PR','rectally (per rectum)'),
(84,'pr','rectally (per rectum)'),
(85,'prn','as needed'),
(86,'PV','in the vagina, vaginally'),
(87,'pv','in the vagina, vaginally'),
(88,'q','every'),
(89,'qam','every morning'),
(90,'qd','every day or once daily'),
(91,'qhs','every night at bedtime, at bedtime nightly'),
(92,'q 4 h','every 4 hours'),
(93,'q 7 PM','every day at 7 PM'),
(94,'qid','four times daily'),
(95,'qn','every night'),
(96,'qod','every other day'),
(97,'qs','sufficient amount'),
(98,'r','rectally'),
(99,'rec','rectally'),
(100,'rept','repeat'),
(101,'rf','refill(s)'),
(102,'s','without'),
(103,'sc','subcutaneous'),
(104,'sid','once daily (written by veterinarians)'),
(105,'Sig','directions'),
(106,'sl','(dissolve) under the tongue'),
(107,'sol','solution'),
(108,'sq','subcutaneous (for injectables)'),
(109,'ss','one-half'),
(110,'ss','sliding scale (for insulin)'),
(111,'stat','immediately'),
(112,'subq','subcutaneous (for injectables)'),
(113,'sub q','subcutaneous (for injectables)'),
(114,'sup','suppository'),
(115,'susp','suspension'),
(116,'sx','symptoms'),
(117,'syr','syrup'),
(118,'tab','tablet(s)'),
(119,'tea','teaspoonful, teaspoonfuls, 5 ml'),
(120,'tbsp','tablespoonful, tablespoonfuls, 15ml'),
(121,'tid','three times daily'),
(122,'tiw','three times weekly (also biw, qiw, etc)'),
(123,'tsp','teaspoonful, teaspoonfuls, 5 ml'),
(124,'tx','treatment'),
(125,'U','unit'),
(126,'u','unit'),
(127,'ud','as directed'),
(128,'utd','as directed'),
(129,'ung','ointment'),
(130,'vag','vaginally, in the vagina'),
(131,'x3d','for 3 days (or maybe 3 doses, caution)'),
(132,'wc','with meals ("with a meal" if once daily dosing)'),
(133,'YO','years old'),
(134,'/','per (example - "Max 5/12 h" = "maximum of 5 per 12 hours")'),
(135,'<','less than'),
(136,'>','greater than');
